import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { NextAuthProvider } from '@/components/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{/* So that we cant use it when it is not logged */}
				<NextAuthProvider> 
					<div className='flex flex-col lg:max-w-[900px] px-8 lg:px-16 mx-auto py-8 shadow-xl min-h-screen text-black'>
						<Navbar />
						<div className='flex-auto'>
							{children}
						</div>
						<Footer />
					</div>
				</NextAuthProvider>
			</body>
		</html>
	)
}
